name: release to prod

on: workflow_dispatch

jobs:
  deploy:
    name: release to prod job
    runs-on: ubuntu-latest

    steps:
      - name: Connect to server, git pull changes
        id: git_pull
        run: |
          sshpass -p "${{ secrets.PROD_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.PROD_USER }}@${{ secrets.PROD_IP }} << 'ENDSSH'
            cd espo-cicd
            sudo git pull origin main
          ENDSSH

      - name: Connect to server, copy changes to espo root directory, rebuild
        id: copy_rebuild
        run: |
          sshpass -p "${{ secrets.PROD_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.PROD_USER }}@${{ secrets.PROD_IP }} << 'ENDSSH'
            sudo cp -rf espo-cicd/* /var/www/espocrm/data/espocrm/
            cd /var/www/espocrm/data/espocrm
            sudo chown -R www-data:www-data .
            sudo /var/www/espocrm/command.sh rebuild
          ENDSSH

      - name: Connect to server, import
        id: import
        run: |
          sshpass -p "${{ secrets.PROD_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.PROD_USER }}@${{ secrets.PROD_IP }} << 'ENDSSH'
            cd /var/www/espocrm/data/espocrm
            sudo docker exec -t espocrm sh -c "bin/command export-import import --format=json --import-path=\"build/ExportImport/Export\" --import-type=createAndUpdate"
          ENDSSH