name: release to prod

on: workflow_dispatch

jobs:
  deploy:
    name: release to prod job
    runs-on: ubuntu-latest

    steps:
      - name: Connect to server, git pull changes
        id: export_import
        run: |
          sshpass -p "${{ secrets.PROD_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.PROD_USER }}@${{ secrets.PROD_IP }} << 'ENDSSH'
            cd /var/www/espocrm/data/espocrm
            sudo chmod +x bin/command
            sudo git pull --force
          ENDSSH

      - name: Connect to server, rebuild
        id: rebuild_espo
        run: |
          sshpass -p "${{ secrets.PROD_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.PROD_USER }}@${{ secrets.PROD_IP }} << 'ENDSSH'
            cd /var/www/espocrm/data/espocrm
            sudo /var/www/espocrm/command.sh rebuild
          ENDSSH

      - name: Connect to server, import
        id: import
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP_ADDRESS }} << 'ENDSSH'
            cd /var/www/espocrm/data/espocrm
            sudo docker exec -t espocrm sh -c "bin/command export-import import --format=json --import-path=\"build/ExportImport/Export\" --import-type=createAndUpdate"
          ENDSSH